cn_web/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('codenames.urls'))
]

codenames/urls.py
"""
Urls for codenames app.
"""

from django.urls import path, re_path
from . import views

app_name = "codenames"

urlpatterns = [
    re_path(r"^(?P<group_name>[A-Za-z])/$",
            views.one_group_table_view,
            name="one_group_table"),
    path("<str:group_name>/results/",
         views.one_group_table_view,
         name="one_group_table"),

    path("cup<int:cup_number>/<str:group_name>",
         views.one_group_table_view,
         name="one_group_table"),

    path("", views.all_groups_sorted_tables_view, name="index"),
    path("raw/",
         views.all_groups_unsorted_tables_view,
         name="all_groups_tables"),
    path("results/",
         views.all_groups_sorted_tables_view,
         name="all_groups_tables"),
    path("cup<int:cup_number>/results/",
         views.all_groups_sorted_tables_view,
         name="all_groups_tables"),
    path("<str:group_name>/add_result/", views.add_result,
         name="add_result"),
]

codenames/forms.py
"""
Forms for codenames web app:
- AddResultForm
"""

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .consts import AWAY_TEAM_WORDS_NUMBER, HOME_TEAM_WORDS_NUMBER
from .consts import SCORE_CHOICES
from .models import ResultType


class AddResultForm(forms.Form):
    """
    Form to add result of one game.
    """
    def __init__(self, *args, **kwargs):
        if "games_choices" in kwargs:
            games_choices = kwargs.pop("games_choices")

        super().__init__(*args, **kwargs)

        self.fields["game"] = forms.CharField(
            label=_("Game:"),
            widget=forms.Select(choices=games_choices)
        )

        # GameResult field must be first
        self.order_fields(["game"])

    result_type = forms.ModelChoiceField(
        label=_("Result type:"),
        queryset=ResultType.objects.all(),
        widget=forms.Select(
            attrs={"onchange": "updateFieldsStates();"}
        )
    )

    score = forms.CharField(
        label=_("Score:"),
        widget=forms.Select(choices=[sc for sc in SCORE_CHOICES if sc[0] >= 0]),
        initial=0
    )

    home_team_fouls = forms.IntegerField(
        label=_("Team 1 fouls:"),
        min_value=0,
        max_value=AWAY_TEAM_WORDS_NUMBER,
        initial=0
    )
    away_team_fouls = forms.IntegerField(
        label=_("Team 2 fouls:"),
        min_value=0,
        max_value=HOME_TEAM_WORDS_NUMBER,
        initial=0
    )

    def clean_score(self):
        score = int(self.cleaned_data["score"])
        result_type = self.cleaned_data["result_type"]
        if not result_type.is_home_win:
            score *= -1
        if result_type.is_auto:
            if score != 0:
                self.add_error(
                    "score",
                    ValidationError(
                        _("Do not choose score if game didn't end normally"),
                        code="score not neede")
                )
        else:
            if score == 0:
                self.add_error(
                    "score",
                    ValidationError(_("Please choose score"),
                                    code="score not chosen")
                )
        return score

codenames/views.py
"""
Views for codenames app.
"""

import typing as tp

from django.http import Http404
from django.shortcuts import render
from django.template.defaulttags import register
from django.utils.translation import gettext_lazy as _

from .consts import CURRENT_CUP_NUMBER
from .forms import AddResultForm
from .models import Cup, GameResult, Group, ResultType
from .table_render import render_result_table_content
from .table_render import render_result_table_header
from .table_render import get_recent_games_schedule
from .table_render import get_upcoming_games_schedule


NON_EXISTING_CUP_ERROR_MESSAGE = _("There is no such cup")
NON_EXISTING_GROUP_ERROR_MESSAGE = _("There is no such group")


@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


def start_view(request):
    """
    Start view of tounament website.
    """
    groups = [
        g.name for g in Group.objects.filter(cup__number=CURRENT_CUP_NUMBER,
                                             dummy=False)
    ]
    context = {
        "group_names": groups
    }
    return render(request, "codenames/start_page.html", context)


def all_groups_unsorted_tables_view(request,
                                    *,
                                    cup_number=CURRENT_CUP_NUMBER):
    return all_groups_tables_view(request,
                                  cup_number=cup_number,
                                  do_sort=False)

def all_groups_sorted_tables_view(request,
                                  *,
                                  cup_number=CURRENT_CUP_NUMBER):
    return all_groups_tables_view(request,
                                  cup_number=cup_number,
                                  do_sort=True)



def all_groups_tables_view(request,
                           *,
                           cup_number=CURRENT_CUP_NUMBER,
                           do_sort: bool):
    """
    View with tables of all groups.
    """
    try:
        cup = Cup.objects.get(number=cup_number)
    except Cup.DoesNotExist as cup_no_exist:
        raise Http404(NON_EXISTING_CUP_ERROR_MESSAGE) from cup_no_exist
    cup_groups = Group.objects.filter(cup__number=cup_number, dummy=False)
    group_names: tp.List[str] = sorted(cg.name for cg in cup_groups)

    group_headers = {gn: render_result_table_header(cup_groups.get(name=gn))
                     for gn in group_names}
    group_tables = {gn: render_result_table_content(cup_groups.get(name=gn),
                                                    do_sort)
                    for gn in group_names}

    upcoming_games_lists = {
        gn: get_upcoming_games_schedule(cup_groups.get(name=gn))
        for gn in group_names
    }
    recent_games_lists = {
        gn: get_recent_games_schedule(cup_groups.get(name=gn))
        for gn in group_names
    }

    context = {
        "cup_number": cup.number,
        "group_names": group_names,
        "groups_headers": group_headers,
        "groups_tables": group_tables,
        "upcoming_games": upcoming_games_lists,
        "recent_games": recent_games_lists,
        "path": request.path,
        "update_time": 10,
    }
    return render(request, "codenames/all_groups_tables.html", context)


def one_group_table_view(request, group_name, *,
                         cup_number=CURRENT_CUP_NUMBER):
    """
    View with table of one group.
    """
    group_name = group_name.upper()
    try:
        Cup.objects.get(number=cup_number)
    except Cup.DoesNotExist as cup_no_exist:
        raise Http404(NON_EXISTING_CUP_ERROR_MESSAGE) from cup_no_exist
    try:
        group = Group.objects.get(name=group_name, cup__number=cup_number)
    except Group.DoesNotExist as group_no_exist:
        raise Http404(NON_EXISTING_GROUP_ERROR_MESSAGE) from group_no_exist

    group_header = render_result_table_header(group)
    group_table = render_result_table_content(group, do_sort=True)

    upcoming_games_list = get_upcoming_games_schedule(group)
    recent_games_list = get_recent_games_schedule(group)

    context = {
        "cup_number": cup_number,
        "group_name": group.name,
        "group_header": group_header,
        "group_table": group_table,
        "upcoming_games": upcoming_games_list,
        "recent_games": recent_games_list,
        "update_time": 10,
    }
    return render(request, "codenames/one_group_table.html", context)


def get_games_choices(group_name: str):
    games_list = sorted(
        GameResult.objects.filter(
            group__name=group_name,
            group__cup__number=CURRENT_CUP_NUMBER),
        key=lambda x: (x.is_finished, x.round_number, x.arena.short))
    return [
        (game.id, game) for game in games_list
    ]


def add_result(request, group_name: str):
    last_add_result: tp.Optional[str] = None
    if request.method == "POST":
        form = AddResultForm(request.POST,
                             games_choices=get_games_choices(group_name))
        if form.is_valid():
            data = request.POST

            result_type = ResultType.objects.get(id=data["result_type"])
            if result_type.do_delete:
                game = GameResult.objects.get(id=int(data["game"]))
                if game.is_finished:
                    GameResult.objects.filter(id=int(data["game"])).update(
                        result_type=None,
                        score=0,
                        home_team_fouls=0,
                        away_team_fouls=0
                    )
                    last_add_result = _("Result deleted successfully!")
                else:
                    last_add_result = _("Game isn't finished yet!")
            else:
                score = int(data["score"])
                if result_type.is_away_win:
                    score *= -1
                GameResult.objects.filter(id=int(data["game"])).update(
                    result_type=data["result_type"],
                    score=score,
                    home_team_fouls=data["home_team_fouls"],
                    away_team_fouls=data["away_team_fouls"],
                )
                last_add_result = _("Result added successfully!")
            form = AddResultForm(games_choices=get_games_choices(group_name))
        else:
            last_add_result = _("Failed to add result!")
    elif request.method == "GET" or form.is_valid():
        form = AddResultForm(games_choices=get_games_choices(group_name))

    ids_to_hide_score: tp.List[int] = [
        rt.id for rt in ResultType.objects.all() if rt.is_auto
    ]
    ids_to_hide_fouls: tp.List[int] = [
        rt.id for rt in ResultType.objects.all() if rt.abbr.startswith("A")
    ] + [
        rt.id for rt in ResultType.objects.all() if rt.abbr == "DE"
    ]

    context = {
        "group_name": group_name,
        "last_add_result": last_add_result,
        "form": form,
        "ids_to_hide_score": ids_to_hide_score,
        "ids_to_hide_fouls": ids_to_hide_fouls,
    }
    return render(request, "codenames/add_result.html", context)

codenames/templates/codenames/add_result.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добавить результат в группу {{ group_name }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'codenames/style.css' %}">
</head>
<body>
    {% if last_add_result %}
    <p>{{ last_add_result }}</p>
    {% endif %}
    <div class="container">
        <form action="{% url 'codenames:add_result' group_name %}" method="post">
            {% csrf_token %}

            {{ form.non_field_errors }}

            {% for hidden_field in form.hidden_fields %}
                {{ hidden_field.errors }}
                {{ hidden_field }}
            {% endfor %}

            {% for field in form.visible_fields %}
            <div class="row">
                <div class="col-25">
                    <label for="{{ field.id_for_label }}" id="label_{{ field.id_for_label }}">
                    {{ field.label }}
                    </label>
                </div>
                <div class="col-75">
                    {% for error in field.errors%}
                    {{ error}}<br>
                    {% endfor %}
                    {{ field }}
                    {{ field.help_text }}
                </div>
            </div>
            {% endfor %}

            <div class="row">
                <div class="col-100">
                    <input type="submit" value="Submit">
                </div>
            </div>
        </form>
    </div>

<script>
function updateFieldsStates() {
    var ids_to_hide_score = {{ ids_to_hide_score }};
    var ids_to_hide_fouls = {{ ids_to_hide_fouls }};
    var result_id = Number(document.getElementById("id_result_type").value);
    var score_field = document.getElementById("id_score");
    var score_label = document.getElementById("label_id_score");
    if (ids_to_hide_score.indexOf(result_id) != -1)
    {
        score_field.style.visibility = "hidden";
        score_label.style.visibility = "hidden";
        score_field.value = 0;
    } else {
        score_field.style.visibility = "visible"
        score_label.style.visibility = "visible"
        score_field.value = 0;
    }
    var home_fouls_field = document.getElementById("id_home_team_fouls");
    var home_fouls_label = document.getElementById("label_id_home_team_fouls");
    var away_fouls_field = document.getElementById("id_away_team_fouls");
    var away_fouls_label = document.getElementById("label_id_away_team_fouls");
    if (ids_to_hide_fouls.indexOf(result_id) != -1)
    {
        home_fouls_field.style.visibility = "hidden";
        home_fouls_label.style.visibility = "hidden";
        home_fouls_field.value = 0;

        away_fouls_field.style.visibility = "hidden";
        away_fouls_label.style.visibility = "hidden";
        away_fouls_field.value = 0;
    } else {
        home_fouls_field.style.visibility = "visible"
        home_fouls_label.style.visibility = "visible"

        away_fouls_field.style.visibility = "visible"
        away_fouls_label.style.visibility = "visible"
    }
}
</script>

</body>
</html>

codenames/templates/codenames/all_groups_tables.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="refresh" content="{{ update_time }}; URL={{ path }}">
    <title>Результаты группового этапа</title>
    <link rel="stylesheet" type="text/css" href="{% static 'codenames/style.css' %}">
</head>
<body>
    {% for group_name in group_names %}
        <div>Группа {{ group_name }}</div><br>
        <div class="container">
            <div class="row">
                <table>
                <tr>
                    {% for cell in groups_headers|get_item:group_name %}
                    <th {% if cell.class_ %} class="{{ cell.class_ }}"{% endif %}>
                        <div {% if cell.title %}title="{{ cell.title }}"{% endif %}>
                            {{ cell.content }}
                        </div>
                    </th>
                    {% endfor %}
                </tr>
                {% for row in groups_tables|get_item:group_name %}
                <tr>
                    {% for cell in row %}
                    <td {% if cell.class_ %} class="{{ cell.class_ }}"{% endif %}>
                        <div {% if cell.title %}title="{{ cell.title }}"{% endif %}>
                            {{ cell.content }}
                        </div>
                    </td>
                    {% endfor %}
                </tr>
                {% endfor %}
                </table>
            </div>
        </div>

        <br>

        {% if upcoming_games|get_item:group_name %}
        <div class="container">
            <div class="row">
                <div class="col-100">
                    <b>Ближайшие матчи:</b>
                </div>
            </div>
            {% for round in upcoming_games|get_item:group_name %}
                <div class="row">
                    <div class="col-100">
                        <b>Тур {{ round.0 }}:</b>
                    </div>
                    {% for game in round.1 %}
                    <div class="col-100">
                        {{ game.scheduled_long }}
                    </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
        {% endif %}
        
        <br>

        {% if recent_games|get_item:group_name %}
        <div class="container">
            <div class="row">
                <div class="col-100">
                    <b>Сыгранные матчи:</b>
                </div>
            </div>
            {% for round in recent_games|get_item:group_name %}
                <div class="row">
                    <div class="col-100">
                        <b>Тур {{ round.0 }}:</b>
                    </div>
                    {% for game in round.1 %}
                    <div class="col-100">
                        {{ game.finished_long }}
                    </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
        {% endif %}
    {% endfor %}
</body>
</html>

codenames/templates/codenames/one_group_table.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="refresh" content="{{ update_time }}; URL={% url 'codenames:one_group_table' group_name %}">
    <title>Результаты группы {{ group_name }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'codenames/style.css' %}">
</head>
<body>
    <div class="container">
        <div class="row">
            <table>
            <tr>
                {% for cell in group_header %}
                <th {% if cell.class_ %} class="{{ cell.class_ }}"{% endif %}>
                    <div {% if cell.title %}title="{{ cell.title }}"{% endif %}>
                        {{ cell.content }}
                    </div>
                </th>
                {% endfor %}
            </tr>
            {% for row in group_table %}
            <tr>
                {% for cell in row %}
                <td {% if cell.class_ %} class="{{ cell.class_ }}"{% endif %}>
                    <div {% if cell.title %}title="{{ cell.title }}"{% endif %}>
                        {{ cell.content }}
                    </div>
                </td>
                {% endfor %}
            </tr>
            {% endfor %}
            </table>
        </div>
    </div>

    <br>

    {% if upcoming_games %}
    <div class="container">
        <div class="row">
            <div class="col-100">
                <b>Ближайшие матчи:</b>
            </div>
        </div>
        {% for round in upcoming_games %}
            <div class="row">
                <div class="col-100">
                    <b>Тур {{ round.0 }}:</b>
                </div>
                {% for game in round.1 %}
                <div class="col-100">
                    {{ game.scheduled_long }}
                </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
    {% endif %}
    
    <br>

    {% if recent_games %}
    <div class="container">
        <div class="row">
            <div class="col-100">
                <b>Сыгранные матчи:</b>
            </div>
        </div>
        {% for round in recent_games %}
            <div class="row">
                <div class="col-100">
                    <b>Тур {{ round.0 }}:</b>
                </div>
                {% for game in round.1 %}
                <div class="col-100">
                    {{ game.finished_long }}
                </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
    {% endif %}
</body>
</html>

codenames/templates/codenames/start_page.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Стартовая страница Codenames Cup</title>
    <link rel="stylesheet" type="text/css" href="{% static 'codenames/style.css' %}">
</head>
<body>
    <a href="{% url 'codenames:all_groups_tables' %}">Все результаты</a>
    {% if group_names %}
    <ul>
    {% for group_name in group_names %}
    <li><a href="{% url 'codenames:one_group_table' group_name %}">Группа {{group_name}}</a></li>
    {% endfor %}
    </ul>
    {% endif %}
</body>
</html>